version: '2.10.2'
name: book-my-look
services:
  db:
    container_name: db
    image: postgres:14.0-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: book-my-look-docker
    ports:
      - 5435:5432  # Change the mapping to a custom port, such as 5435
    expose:
      - 5435
    volumes:
      - db:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    networks:
      - db

  backend:
    container_name: backend
    build: ./book-my-look
    restart: always
    ports:
      - 8080:8080
    expose:
      - 8080
    depends_on:
      - db
    networks:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/book-my-look-docker  # Update the port here as well
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root


volumes:
  db:
    driver: local

networks:
  db:



